from manim import *
from Scenes.tautochrone import *
from Scenes.brachistochrone import *
from Scenes.beltrami import *
from Scenes.cycloid import *

###NOTE: Keep in mind that the render will be long, so you might want to split it into multiple classes if you want to keep track of the code. I will just put everything in one class for some rendering purposes.

class Video(Scene):
    def construct(self):

        #Intro
        self.play(Create(rect), Write(PROBLEM), run_time=5)
        self.wait(5)
        self.play(Write(t))
        self.play(Flash(t, line_length=0.5, num_lines=50, color=GREEN, flash_radius=1.1, time_width=0.5, run_time=2, rate_func = rush_from))
        self.play(FadeOut(PROBLEM, t, rect))
        self.clear()

        #Brachistochrone Intro

        self.play(Write(brachisto))
        self.play(Write(brachisto0.next_to(brachisto, DOWN)))
        self.play(Write(r1))
        self.wait(2)
        self.play(FadeOut(brachisto, brachisto0, r1))
        self.clear()

        #Brachistochrone Graph

        self.play(Create(brachistochrone1), Create(straight), Create(arcf))
        self.play(Write(start_label), Write(end_label))
        self.play(Write(rendered_code1), Write(rendered_code2.next_to(rendered_code1, LEFT)), Write(rendered_code3.next_to(rendered_code1, DOWN)))
        self.play(MoveAlongPath(dot1, brachistochrone1, rate_func=acceleration2), MoveAlongPath(dot2, straight, rate_func=acceleration2), MoveAlongPath(dot3, arcf, rate_func=acceleration2), run_time=2)
        self.play(Write(a0))
        self.play(Write(binfo))
        self.wait(2)
        self.play(Write(bstart))
        self.play(Flash(bstart, line_length=0.5, num_lines=50, color=BLUE, flash_radius=1.1, time_width=0.5, run_time=2, rate_func = rush_from))
        self.play(FadeOut(brachistochrone1, straight, arcf, start_label, end_label, rendered_code1, rendered_code2, rendered_code3, dot1, dot2, dot3, a0, binfo, bstart))
        self.clear()
 
        #Brachistochrone

        start0(self)
        self.play(Write(b00))
        self.play(Write(b01), Create(b04))
        self.play(Write(b02))
        self.wait(3)
        self.remove(b04)
        self.play(Write(b03))
        self.play(FadeOut(b00, b01, b02, b03, t62))
        self.clear()

        #Beltrami

        self.play(Write(b1))
        self.play(Write(b10),Write(b11.next_to(b10, UP)))
        self.wait(1)
        self.play(FadeOut(b10), FadeOut(b11), ReplacementTransform(b1,b2))
        self.play(ReplacementTransform(b2,b20))
        self.play(Write(b3))
        self.wait(1)
        self.play(ReplacementTransform(b3,b4))
        self.wait(1)
        self.play(FadeOut(b20[0][15::],b4[0][15::]), b20[0][:15].animate.move_to(b4[0][15::].get_center() + RIGHT*0.8).set_color(WHITE))
        self.wait(1)
        self.play(b204.animate.to_corner(UL).set_color(GREEN))
        self.play(Write(b5))
        self.wait(1)
        self.play(FadeOut(b5[0][25::], b204[1]), b204[0].animate.move_to(b5[0][25::].get_center() + RIGHT*0.1).set_color(RED))
        self.wait(1)
        arc = ArcBetweenPoints(b204[0][:5].get_center(), b5[0][14].get_center() + RIGHT*0.7, angle=PI)
        self.wait(1)
        self.play(FadeOut(b5[0][15:25], b204[0][5::]), MoveAlongPath(b204[0][:5], arc), b5[0][14].animate.move_to(RIGHT*0.6), Write(b50.next_to(b5[0][13], RIGHT)))
        self.play(Write(b51.next_to(b5[0][14], RIGHT)))
        self.wait(1)
        self.play(ReplacementTransform(VGroup(b204[0][:5], b5[0][:15], b50, b51), b6))
        self.wait(1)
        self.play(ReplacementTransform(b6, b7))
        self.play(TransformMatchingShapes(b7, b8))

        #Brachistochrone 2

        self.play(b8.animate.to_corner(UL).set_color(GREEN))
        self.play(Write(j1))
        self.play(j1.animate.shift(DOWN), Write(j2))
        self.wait(3)
        jgroup = VGroup(b8, j1, j2)
        self.play(TransformMatchingShapes(jgroup, j3))
        self.wait(1)
        self.play(TransformMatchingShapes(j3, j4))
        self.wait(1)
        self.play(TransformMatchingShapes(j4, j5))
        self.wait(1)
        self.play(TransformMatchingShapes(j5, j6))
        self.wait(1)
        self.play(Write(j7), ReplacementTransform(j6, j8))
        self.play(TransformMatchingShapes(j8, j9))
        self.wait(2)
        self.play(FadeOut(j7))
        self.play(TransformMatchingShapes(j9, j10))
        self.play(TransformMatchingShapes(j10, j11))
        self.play(TransformMatchingShapes(j11, j12))
        self.wait(2)
        self.play(Write(j13))
        self.wait(2)
        self.play(FadeOut(j13), TransformMatchingShapes(j12, j14))
        self.play(j14.animate.to_corner(UL).set_color(PURE_RED))
        self.play(Write(j15))
        self.play(Write(j16))
        self.play(Write(j17))
        self.wait(2)
        self.play(TransformMatchingShapes(VGroup(j14,j15), j18))
        self.play(FadeOut(j17))
        self.play(TransformMatchingShapes(VGroup(j18,j16), j19))
        self.play(j19.animate.move_to(ORIGIN))
        self.wait(2)
        self.play(TransformMatchingShapes(j19, j20))
        self.play(TransformMatchingShapes(j20, j21))
        self.play(TransformMatchingShapes(j21, j22))
        self.wait(2)
        self.play(Write(j23))
        self.play(TransformMatchingShapes(j23, j24))
        self.wait(2)
        self.play(TransformMatchingShapes(VGroup(j24[0][11::], j22), j25))
        self.play(FadeOut(j24[0][:11]))
        self.wait(2)
        self.play(TransformMatchingShapes(j25, j26))
        self.play(TransformMatchingShapes(j26, j27))
        self.play(Write(j28))
        self.wait(2)
        self.play(Write(j29))
        self.play(TransformMatchingShapes(j27, j30))
        self.play(Write(j31))
        self.wait(1)
        self.play(TransformMatchingTex(VGroup(j28, j31), j32))
        self.wait(1)
        self.play(ReplacementTransform(j29, j33))
        self.wait(1)
        self.play(TransformMatchingShapes(j30, j34), TransformMatchingShapes(j32, j35))
        self.play(TransformMatchingShapes(j34, j36), TransformMatchingShapes(j35, j37))
        self.play(Create(endrect), run_time=3)
        self.play(Write(j38))
        self.wait(2)
        self.play(FadeOut(j33, j36, j37, j38, endrect))
        self.clear()

        #Tautochrone Intro

        self.play(Write(tauto))
        self.play(Write(tauto0.next_to(tauto, DOWN)))
        self.play(Write(t0))
        self.wait(2)
        self.play(FadeOut(tauto, tauto0, t0))
        self.clear()

        #Tautochrone Graph
 
        self.play(Create(brachistochrone1))
        self.play(Write(start_label), Write(end_label))
        self.play(Write(rendered_code0))
        self.play(Write(tinfo))
        self.play(MoveAlongPath(dot1, brachistochrone1), MoveAlongPath(dot2, brachistochrone2), MoveAlongPath(dot3, brachistochrone3), run_time=4, rate_func=acceleration2)
        self.wait(2)
        self.play(Write(tstart))
        self.play(Flash(tstart, line_length=0.5, num_lines=50, color=ORANGE, flash_radius=1.1, time_width=0.5, run_time=2, rate_func = rush_from))
        self.play(FadeOut(brachistochrone1, start_label, end_label, rendered_code0, dot1, dot2, dot3, tinfo, tstart))
        self.clear()

        #Tautochrone

        start0(self)
        self.play(Write(t7))
        self.wait(2)
        self.play(Write(t8))
        self.wait(2)
        self.play(FadeOut(t7), TransformMatchingShapes(t62, t9))
        self.wait(2)
        fakebreakpoint = VGroup(t8, t9)
        self.play(ClockwiseTransform(fakebreakpoint, t10))
        self.wait(1)
        for a, b in zip([fakebreakpoint, t11, t12, t13, t14, t15], [t11, t12, t13, t14, t15, t16]): self.play(TransformMatchingShapes(a, b))
        self.play(t16.animate.shift(UP))
        self.play(DrawBorderThenFill(t17))
        self.play(t16.animate.shift(UP), t17.animate.shift(UP), DrawBorderThenFill(t18))
        self.wait(3)
        self.play(FadeOut(t16, t17, t18))
        self.play(Write(t19))
        for a, b in [(t19, t20), (t20, t21), (t21,t211), (t211, t22), (t22, t23)]: self.wait(1); self.play(TransformMatchingShapes(a, b))
        self.play(t23.animate.to_corner(UL))
        self.wait(1)
        self.play(Write(t24), run_time=3)
        self.play(TransformMatchingShapes(t24 , t25))
        self.play(TransformMatchingShapes(VGroup(t23, t25), t26), run_time=3)
        self.play(TransformMatchingShapes(t26, t27))
        self.wait(1)
        self.play(Write(integralinfo))
        self.wait(2)
        self.play(Write(integralsub))
        self.wait(2)
        self.play(Write(integralsub2))
        self.play(FadeOut(integralinfo), Write(integralsub3))
        self.wait(2)
        self.play(TransformMatchingShapes(t27, t28))
        self.wait(2)
        self.play(TransformMatchingShapes(VGroup(t28, integralsub, integralsub2), t29))
        self.wait(1)
        self.play(DrawBorderThenFill(t30), FadeOut(integralsub3))
        self.play(TransformMatchingShapes(t29, t31))
        self.wait(1)
        self.play(TransformMatchingShapes(VGroup(t30, t31), t32))
        self.wait(1)
        self.play(DrawBorderThenFill(t33))
        self.play(TransformMatchingShapes(t32, t34))
        self.play(Unwrite(t33))
        self.play(t34.animate.to_edge(DOWN).set_color(PURE_RED))
        self.play(Create(ax))
        self.play(Create(cyc))
        self.play(Create(end_point), FadeIn(dotlabelcyc))
        self.play(MoveAlongPath(dot2cyc, cyc), MaintainPositionRelativeTo(dot2labelcyc, dot2cyc), run_time=5, rate_func = rate_functions.ease_in_bounce)
        self.play(Write(t35))
        self.wait(1)
        jjj = cancel(t34[0][9::])
        self.play(Create(jjj), Write(addendum))
        self.play(TransformMatchingShapes(t34[0][0:9], t36), FadeOut(t34[0][9::], jjj), MaintainPositionRelativeTo(dotlabelcyc, end_point), UpdateFromAlphaFunc(cyc, update_cycloid_and_dot),run_time=5)
        self.play(ReplacementTransform(t35, t37), FadeOut(addendum))
        self.wait(3)
        self.play(FadeOut(t36, t37, cyc, ax, end_point, dotlabelcyc, dot2cyc, dot2labelcyc))
        self.play(GrowFromCenter(helpmeout), run_time=2)
        self.play(FadeOut(helpmeout, scale=6))
        self.clear()

        #Cycloid

        self.play(Create(axes), Create(diagonallines))
        self.play(Create(circle), Create(dot), Create(path), Write(info))
        self.add(radius, centerline, centerr, perpendicularline, groundline, angle)
        update_all()
        centerr.add_updater(update_centerr)
        self.wait(1)
        remove_all()
        r2 = MathTex(r"r").next_to(radius.get_center(), 0.8*UL + 0.2*RIGHT)
        theta = MathTex(r"\theta", font_size=36).set_color(BLUE).next_to(circle.get_center(), 2*DL + 0.65*RIGHT)
        rsint = MathTex(r"r\sin\theta", font_size=36).next_to(perpendicularline.get_center(), 0.6*DOWN)
        rcost = MathTex(r"r\cos\theta", font_size=36).next_to(circle.get_center(), DR + 0.4*DOWN + 0.1*LEFT)
        rt = MathTex(r"r\theta", font_size=36).next_to(groundline.get_center(), 2.2*DOWN)
        inal = VGroup(centerr, rsint, rcost, rt, minus, minus2, xc, yc, info2)
        rsint[0][4].set_color(BLUE)
        rcost[0][4].set_color(BLUE)
        rt[0][1].set_color(BLUE)
        self.play(Write(r2), Write(theta), Write(rsint), Write(rcost), Write(rt))
        self.play(Write(info2))
        self.play(rt.animate.next_to(info2).scale(48 / 36))
        self.play(Write(minus.next_to(rt)))
        self.play(rsint.animate.next_to(minus, 1.3*RIGHT).scale(48 / 36))
        centerr.remove_updater(update_centerr)
        self.play(centerr.animate.next_to(rt, DOWN))
        self.play(Write(minus2.next_to(centerr)))
        self.play(rcost.animate.next_to(minus2, 1.3*RIGHT).scale(48 / 36))
        self.play(Write(xc.next_to(rcost)), Write(yc.next_to(rsint)))
        self.wait(3)
        self.play(TransformMatchingShapes(inal, final))
        self.wait(2)
        self.play(Unwrite(r2), Unwrite(theta))
        update_all()
        self.wait(7)
        self.play(FadeOut(axes, diagonallines, path, info, groundline, final))
        self.clear()            

        #Outro

        self.play(Write(end, run_time=7))
        self.play(DrawBorderThenFill(endgroup))
        self.wait(3.5)
        self.play(FadeOut(end, endgroup), DrawBorderThenFill(tfw))
        self.wait(6)